version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: voyager-postgres
    restart: unless-stopped
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: voyager
      POSTGRES_PASSWORD: voyager
      POSTGRES_DB: voyager
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    networks:
      - voyager-network

  redis:
    image: redis:7-alpine
    container_name: voyager-redis
    restart: unless-stopped
    networks:
      - voyager-network

  voyager:  
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: voyager-service
    restart: unless-stopped
    ports:
      - "52060:52060"
    environment:
      DATABASE_URL: postgresql://voyager:voyager@postgres:5432/voyager
      SEARCH_DATABASE_URL: postgresql://voyager:voyager@postgres:5432/voyager-search
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    depends_on:
      - postgres
      - redis
    networks:
      - voyager-network

volumes:
  postgres_data2:
    driver: local

networks:
  voyager-network:
    driver: bridge
